In [1]:
import tubesml as tml
import pandas as pd
import numpy as np

from source.report import _point_to_proba

from sklearn.metrics import brier_score_loss, mean_squared_error

from sklearn.model_selection import KFold

from sklearn.linear_model import Ridge, LogisticRegression, Lasso
from sklearn.pipeline import Pipeline

import lightgbm as lgb
import xgboost as xgb

import optuna
from optuna.samplers import TPESampler

In [2]:
df = pd.read_csv('data/processed/full_training.csv')

N_FOLDS = 5
kfolds = KFold(n_splits=N_FOLDS, shuffle=True, random_state=13)

df_train, df_test = tml.make_test(df, test_size=0.2, random_state=34)

DROP = ["target", "target_points", "ID", "DayNum", "Team1", "Team2",
        'T1_Loc', 'T2_Loc',
                "T1_region", "T2_region", "Season", "delta_Loc",
                "Season", "competitive", "competitive_score",
                "delta_def_rating_diff", "delta_impact_diff",
                "T1_def_rating_diff", "T2_def_rating_diff"]

df_train.head()

df_train = df.copy()

## Feats cats

In [3]:
all_feats = [c for c in df_train if c not in DROP]
all_feats

['T1_Ast',
 'T1_Ast_TO_ratio',
 'T1_Ast_TO_ratio_diff',
 'T1_Ast_diff',
 'T1_Away',
 'T1_Blk',
 'T1_Blk_diff',
 'T1_DR',
 'T1_DR_diff',
 'T1_DR_opportunity',
 'T1_DR_opportunity_diff',
 'T1_Eff_FG_perc_diff',
 'T1_FG3_ratio',
 'T1_FG3_ratio_diff',
 'T1_FGA',
 'T1_FGA2',
 'T1_FGA2_diff',
 'T1_FGA3',
 'T1_FGA3_diff',
 'T1_FGA_diff',
 'T1_FGM',
 'T1_FGM2',
 'T1_FGM2_diff',
 'T1_FGM3',
 'T1_FGM3_diff',
 'T1_FGM_diff',
 'T1_FGM_no_ast',
 'T1_FGM_no_ast_diff',
 'T1_FTA',
 'T1_FTA_diff',
 'T1_FTM',
 'T1_FTM_diff',
 'T1_N_wins',
 'T1_OR',
 'T1_OR_diff',
 'T1_OR_opportunity',
 'T1_OR_opportunity_diff',
 'T1_OT_win',
 'T1_PF',
 'T1_PF_diff',
 'T1_Score',
 'T1_Score_diff',
 'T1_Stl',
 'T1_Stl_diff',
 'T1_TO',
 'T1_TO_diff',
 'T1_TO_perposs',
 'T1_TO_perposs_diff',
 'T1_Tot_Reb',
 'T1_Tot_Reb_diff',
 'T1_True_shooting_perc_diff',
 'T1_def_rating',
 'T1_impact',
 'T1_impact_diff',
 'T1_off_rating',
 'T1_off_rating_diff',
 'T1_opp_FGA',
 'T1_opp_FGM',
 'T1_opp_FGM3',
 'T1_opp_FTA',
 'T1_opp_PF',
 'T1_opp_TO',
 'T1_opp_possessions',
 'T1_opp_score',
 'T1_opp_shtg_opportunity',
 'T1_possessions',
 'T1_possessions_diff',
 'T1_shtg_opportunity',
 'T1_shtg_opportunity_diff',
 'T1_FGM_perc',
 'T1_FGM2_perc',
 'T1_FGM3_perc',
 'T1_FT_perc',
 'T1_FGM_no_ast_perc',
 'T1_True_shooting_perc',
 'T1_Opp_True_shooting_perc',
 'T1_Eff_shooting_perc',
 'T1_Opp_eff_shooting_perc',
 'T1_OT_win_perc',
 'T1_Seed',
 'T1_elo',
 'T2_Ast',
 'T2_Ast_TO_ratio',
 'T2_Ast_TO_ratio_diff',
 'T2_Ast_diff',
 'T2_Away',
 'T2_Blk',
 'T2_Blk_diff',
 'T2_DR',
 'T2_DR_diff',
 'T2_DR_opportunity',
 'T2_DR_opportunity_diff',
 'T2_Eff_FG_perc_diff',
 'T2_FG3_ratio',
 'T2_FG3_ratio_diff',
 'T2_FGA',
 'T2_FGA2',
 'T2_FGA2_diff',
 'T2_FGA3',
 'T2_FGA3_diff',
 'T2_FGA_diff',
 'T2_FGM',
 'T2_FGM2',
 'T2_FGM2_diff',
 'T2_FGM3',
 'T2_FGM3_diff',
 'T2_FGM_diff',
 'T2_FGM_no_ast',
 'T2_FGM_no_ast_diff',
 'T2_FTA',
 'T2_FTA_diff',
 'T2_FTM',
 'T2_FTM_diff',
 'T2_N_wins',
 'T2_OR',
 'T2_OR_diff',
 'T2_OR_opportunity',
 'T2_OR_opportunity_diff',
 'T2_OT_win',
 'T2_PF',
 'T2_PF_diff',
 'T2_Score',
 'T2_Score_diff',
 'T2_Stl',
 'T2_Stl_diff',
 'T2_TO',
 'T2_TO_diff',
 'T2_TO_perposs',
 'T2_TO_perposs_diff',
 'T2_Tot_Reb',
 'T2_Tot_Reb_diff',
 'T2_True_shooting_perc_diff',
 'T2_def_rating',
 'T2_impact',
 'T2_impact_diff',
 'T2_off_rating',
 'T2_off_rating_diff',
 'T2_opp_FGA',
 'T2_opp_FGM',
 'T2_opp_FGM3',
 'T2_opp_FTA',
 'T2_opp_PF',
 'T2_opp_TO',
 'T2_opp_possessions',
 'T2_opp_score',
 'T2_opp_shtg_opportunity',
 'T2_possessions',
 'T2_possessions_diff',
 'T2_shtg_opportunity',
 'T2_shtg_opportunity_diff',
 'T2_FGM_perc',
 'T2_FGM2_perc',
 'T2_FGM3_perc',
 'T2_FT_perc',
 'T2_FGM_no_ast_perc',
 'T2_True_shooting_perc',
 'T2_Opp_True_shooting_perc',
 'T2_Eff_shooting_perc',
 'T2_Opp_eff_shooting_perc',
 'T2_OT_win_perc',
 'T2_Seed',
 'T2_elo',
 'delta_Ast',
 'delta_Ast_TO_ratio',
 'delta_Ast_TO_ratio_diff',
 'delta_Ast_diff',
 'delta_Away',
 'delta_Blk',
 'delta_Blk_diff',
 'delta_DR',
 'delta_DR_diff',
 'delta_DR_opportunity',
 'delta_DR_opportunity_diff',
 'delta_Eff_FG_perc_diff',
 'delta_FG3_ratio',
 'delta_FG3_ratio_diff',
 'delta_FGA',
 'delta_FGA2',
 'delta_FGA2_diff',
 'delta_FGA3',
 'delta_FGA3_diff',
 'delta_FGA_diff',
 'delta_FGM',
 'delta_FGM2',
 'delta_FGM2_diff',
 'delta_FGM3',
 'delta_FGM3_diff',
 'delta_FGM_diff',
 'delta_FGM_no_ast',
 'delta_FGM_no_ast_diff',
 'delta_FTA',
 'delta_FTA_diff',
 'delta_FTM',
 'delta_FTM_diff',
 'delta_N_wins',
 'delta_OR',
 'delta_OR_diff',
 'delta_OR_opportunity',
 'delta_OR_opportunity_diff',
 'delta_OT_win',
 'delta_PF',
 'delta_PF_diff',
 'delta_Score',
 'delta_Score_diff',
 'delta_Stl',
 'delta_Stl_diff',
 'delta_TO',
 'delta_TO_diff',
 'delta_TO_perposs',
 'delta_TO_perposs_diff',
 'delta_Tot_Reb',
 'delta_Tot_Reb_diff',
 'delta_True_shooting_perc_diff',
 'delta_def_rating',
 'delta_impact',
 'delta_off_rating',
 'delta_off_rating_diff',
 'delta_opp_FGA',
 'delta_opp_FGM',
 'delta_opp_FGM3',
 'delta_opp_FTA',
 'delta_opp_PF',
 'delta_opp_TO',
 'delta_opp_possessions',
 'delta_opp_score',
 'delta_opp_shtg_opportunity',
 'delta_possessions',
 'delta_possessions_diff',
 'delta_shtg_opportunity',
 'delta_shtg_opportunity_diff',
 'delta_FGM_perc',
 'delta_FGM2_perc',
 'delta_FGM3_perc',
 'delta_FT_perc',
 'delta_FGM_no_ast_perc',
 'delta_True_shooting_perc',
 'delta_Opp_True_shooting_perc',
 'delta_Eff_shooting_perc',
 'delta_Opp_eff_shooting_perc',
 'delta_OT_win_perc',
 'delta_Seed',
 'delta_elo',
 'delta_off_edge',
 'delta_def_edge',
 'stage_Round1',
 'stage_Round2',
 'stage_Round3',
 'stage_Round4',
 'stage_final',
 'stage_finalfour',
 'stage_impossible',
 'T1_quality',
 'T2_quality',
 'delta_quality',
 'tourney']

In [4]:
all_delta = [c for c in df_train if c not in DROP and "delta" in c]

all_delta

['delta_Ast',
 'delta_Ast_TO_ratio',
 'delta_Ast_TO_ratio_diff',
 'delta_Ast_diff',
 'delta_Away',
 'delta_Blk',
 'delta_Blk_diff',
 'delta_DR',
 'delta_DR_diff',
 'delta_DR_opportunity',
 'delta_DR_opportunity_diff',
 'delta_Eff_FG_perc_diff',
 'delta_FG3_ratio',
 'delta_FG3_ratio_diff',
 'delta_FGA',
 'delta_FGA2',
 'delta_FGA2_diff',
 'delta_FGA3',
 'delta_FGA3_diff',
 'delta_FGA_diff',
 'delta_FGM',
 'delta_FGM2',
 'delta_FGM2_diff',
 'delta_FGM3',
 'delta_FGM3_diff',
 'delta_FGM_diff',
 'delta_FGM_no_ast',
 'delta_FGM_no_ast_diff',
 'delta_FTA',
 'delta_FTA_diff',
 'delta_FTM',
 'delta_FTM_diff',
 'delta_N_wins',
 'delta_OR',
 'delta_OR_diff',
 'delta_OR_opportunity',
 'delta_OR_opportunity_diff',
 'delta_OT_win',
 'delta_PF',
 'delta_PF_diff',
 'delta_Score',
 'delta_Score_diff',
 'delta_Stl',
 'delta_Stl_diff',
 'delta_TO',
 'delta_TO_diff',
 'delta_TO_perposs',
 'delta_TO_perposs_diff',
 'delta_Tot_Reb',
 'delta_Tot_Reb_diff',
 'delta_True_shooting_perc_diff',
 'delta_def_rating',
 'delta_impact',
 'delta_off_rating',
 'delta_off_rating_diff',
 'delta_opp_FGA',
 'delta_opp_FGM',
 'delta_opp_FGM3',
 'delta_opp_FTA',
 'delta_opp_PF',
 'delta_opp_TO',
 'delta_opp_possessions',
 'delta_opp_score',
 'delta_opp_shtg_opportunity',
 'delta_possessions',
 'delta_possessions_diff',
 'delta_shtg_opportunity',
 'delta_shtg_opportunity_diff',
 'delta_FGM_perc',
 'delta_FGM2_perc',
 'delta_FGM3_perc',
 'delta_FT_perc',
 'delta_FGM_no_ast_perc',
 'delta_True_shooting_perc',
 'delta_Opp_True_shooting_perc',
 'delta_Eff_shooting_perc',
 'delta_Opp_eff_shooting_perc',
 'delta_OT_win_perc',
 'delta_Seed',
 'delta_elo',
 'delta_off_edge',
 'delta_def_edge',
 'delta_quality']

In [5]:
no_delta = [c for c in df_train if c not in DROP and "delta" not in c]
no_delta

['T1_Ast',
 'T1_Ast_TO_ratio',
 'T1_Ast_TO_ratio_diff',
 'T1_Ast_diff',
 'T1_Away',
 'T1_Blk',
 'T1_Blk_diff',
 'T1_DR',
 'T1_DR_diff',
 'T1_DR_opportunity',
 'T1_DR_opportunity_diff',
 'T1_Eff_FG_perc_diff',
 'T1_FG3_ratio',
 'T1_FG3_ratio_diff',
 'T1_FGA',
 'T1_FGA2',
 'T1_FGA2_diff',
 'T1_FGA3',
 'T1_FGA3_diff',
 'T1_FGA_diff',
 'T1_FGM',
 'T1_FGM2',
 'T1_FGM2_diff',
 'T1_FGM3',
 'T1_FGM3_diff',
 'T1_FGM_diff',
 'T1_FGM_no_ast',
 'T1_FGM_no_ast_diff',
 'T1_FTA',
 'T1_FTA_diff',
 'T1_FTM',
 'T1_FTM_diff',
 'T1_N_wins',
 'T1_OR',
 'T1_OR_diff',
 'T1_OR_opportunity',
 'T1_OR_opportunity_diff',
 'T1_OT_win',
 'T1_PF',
 'T1_PF_diff',
 'T1_Score',
 'T1_Score_diff',
 'T1_Stl',
 'T1_Stl_diff',
 'T1_TO',
 'T1_TO_diff',
 'T1_TO_perposs',
 'T1_TO_perposs_diff',
 'T1_Tot_Reb',
 'T1_Tot_Reb_diff',
 'T1_True_shooting_perc_diff',
 'T1_def_rating',
 'T1_impact',
 'T1_impact_diff',
 'T1_off_rating',
 'T1_off_rating_diff',
 'T1_opp_FGA',
 'T1_opp_FGM',
 'T1_opp_FGM3',
 'T1_opp_FTA',
 'T1_opp_PF',
 'T1_opp_TO',
 'T1_opp_possessions',
 'T1_opp_score',
 'T1_opp_shtg_opportunity',
 'T1_possessions',
 'T1_possessions_diff',
 'T1_shtg_opportunity',
 'T1_shtg_opportunity_diff',
 'T1_FGM_perc',
 'T1_FGM2_perc',
 'T1_FGM3_perc',
 'T1_FT_perc',
 'T1_FGM_no_ast_perc',
 'T1_True_shooting_perc',
 'T1_Opp_True_shooting_perc',
 'T1_Eff_shooting_perc',
 'T1_Opp_eff_shooting_perc',
 'T1_OT_win_perc',
 'T1_Seed',
 'T1_elo',
 'T2_Ast',
 'T2_Ast_TO_ratio',
 'T2_Ast_TO_ratio_diff',
 'T2_Ast_diff',
 'T2_Away',
 'T2_Blk',
 'T2_Blk_diff',
 'T2_DR',
 'T2_DR_diff',
 'T2_DR_opportunity',
 'T2_DR_opportunity_diff',
 'T2_Eff_FG_perc_diff',
 'T2_FG3_ratio',
 'T2_FG3_ratio_diff',
 'T2_FGA',
 'T2_FGA2',
 'T2_FGA2_diff',
 'T2_FGA3',
 'T2_FGA3_diff',
 'T2_FGA_diff',
 'T2_FGM',
 'T2_FGM2',
 'T2_FGM2_diff',
 'T2_FGM3',
 'T2_FGM3_diff',
 'T2_FGM_diff',
 'T2_FGM_no_ast',
 'T2_FGM_no_ast_diff',
 'T2_FTA',
 'T2_FTA_diff',
 'T2_FTM',
 'T2_FTM_diff',
 'T2_N_wins',
 'T2_OR',
 'T2_OR_diff',
 'T2_OR_opportunity',
 'T2_OR_opportunity_diff',
 'T2_OT_win',
 'T2_PF',
 'T2_PF_diff',
 'T2_Score',
 'T2_Score_diff',
 'T2_Stl',
 'T2_Stl_diff',
 'T2_TO',
 'T2_TO_diff',
 'T2_TO_perposs',
 'T2_TO_perposs_diff',
 'T2_Tot_Reb',
 'T2_Tot_Reb_diff',
 'T2_True_shooting_perc_diff',
 'T2_def_rating',
 'T2_impact',
 'T2_impact_diff',
 'T2_off_rating',
 'T2_off_rating_diff',
 'T2_opp_FGA',
 'T2_opp_FGM',
 'T2_opp_FGM3',
 'T2_opp_FTA',
 'T2_opp_PF',
 'T2_opp_TO',
 'T2_opp_possessions',
 'T2_opp_score',
 'T2_opp_shtg_opportunity',
 'T2_possessions',
 'T2_possessions_diff',
 'T2_shtg_opportunity',
 'T2_shtg_opportunity_diff',
 'T2_FGM_perc',
 'T2_FGM2_perc',
 'T2_FGM3_perc',
 'T2_FT_perc',
 'T2_FGM_no_ast_perc',
 'T2_True_shooting_perc',
 'T2_Opp_True_shooting_perc',
 'T2_Eff_shooting_perc',
 'T2_Opp_eff_shooting_perc',
 'T2_OT_win_perc',
 'T2_Seed',
 'T2_elo',
 'stage_Round1',
 'stage_Round2',
 'stage_Round3',
 'stage_Round4',
 'stage_final',
 'stage_finalfour',
 'stage_impossible',
 'T1_quality',
 'T2_quality',
 'tourney']

In [6]:
seeds = [c for c in df_train if c not in DROP and "Seed" in c] + [c for c in df_train if "quality" in c] + [c for c in df_train if "stage" in c] + [c for c in df_train if "elo" in c] + ["tourney"]
seeds

['T1_Seed',
 'T2_Seed',
 'delta_Seed',
 'T1_quality',
 'T2_quality',
 'delta_quality',
 'stage_Round1',
 'stage_Round2',
 'stage_Round3',
 'stage_Round4',
 'stage_final',
 'stage_finalfour',
 'stage_impossible',
 'T1_elo',
 'T2_elo',
 'delta_elo',
 'tourney']

In [7]:
no_seeds = [c for c in df_train if c not in DROP and "Seed" not in c]
no_seeds

['T1_Ast',
 'T1_Ast_TO_ratio',
 'T1_Ast_TO_ratio_diff',
 'T1_Ast_diff',
 'T1_Away',
 'T1_Blk',
 'T1_Blk_diff',
 'T1_DR',
 'T1_DR_diff',
 'T1_DR_opportunity',
 'T1_DR_opportunity_diff',
 'T1_Eff_FG_perc_diff',
 'T1_FG3_ratio',
 'T1_FG3_ratio_diff',
 'T1_FGA',
 'T1_FGA2',
 'T1_FGA2_diff',
 'T1_FGA3',
 'T1_FGA3_diff',
 'T1_FGA_diff',
 'T1_FGM',
 'T1_FGM2',
 'T1_FGM2_diff',
 'T1_FGM3',
 'T1_FGM3_diff',
 'T1_FGM_diff',
 'T1_FGM_no_ast',
 'T1_FGM_no_ast_diff',
 'T1_FTA',
 'T1_FTA_diff',
 'T1_FTM',
 'T1_FTM_diff',
 'T1_N_wins',
 'T1_OR',
 'T1_OR_diff',
 'T1_OR_opportunity',
 'T1_OR_opportunity_diff',
 'T1_OT_win',
 'T1_PF',
 'T1_PF_diff',
 'T1_Score',
 'T1_Score_diff',
 'T1_Stl',
 'T1_Stl_diff',
 'T1_TO',
 'T1_TO_diff',
 'T1_TO_perposs',
 'T1_TO_perposs_diff',
 'T1_Tot_Reb',
 'T1_Tot_Reb_diff',
 'T1_True_shooting_perc_diff',
 'T1_def_rating',
 'T1_impact',
 'T1_impact_diff',
 'T1_off_rating',
 'T1_off_rating_diff',
 'T1_opp_FGA',
 'T1_opp_FGM',
 'T1_opp_FGM3',
 'T1_opp_FTA',
 'T1_opp_PF',
 'T1_opp_TO',
 'T1_opp_possessions',
 'T1_opp_score',
 'T1_opp_shtg_opportunity',
 'T1_possessions',
 'T1_possessions_diff',
 'T1_shtg_opportunity',
 'T1_shtg_opportunity_diff',
 'T1_FGM_perc',
 'T1_FGM2_perc',
 'T1_FGM3_perc',
 'T1_FT_perc',
 'T1_FGM_no_ast_perc',
 'T1_True_shooting_perc',
 'T1_Opp_True_shooting_perc',
 'T1_Eff_shooting_perc',
 'T1_Opp_eff_shooting_perc',
 'T1_OT_win_perc',
 'T1_elo',
 'T2_Ast',
 'T2_Ast_TO_ratio',
 'T2_Ast_TO_ratio_diff',
 'T2_Ast_diff',
 'T2_Away',
 'T2_Blk',
 'T2_Blk_diff',
 'T2_DR',
 'T2_DR_diff',
 'T2_DR_opportunity',
 'T2_DR_opportunity_diff',
 'T2_Eff_FG_perc_diff',
 'T2_FG3_ratio',
 'T2_FG3_ratio_diff',
 'T2_FGA',
 'T2_FGA2',
 'T2_FGA2_diff',
 'T2_FGA3',
 'T2_FGA3_diff',
 'T2_FGA_diff',
 'T2_FGM',
 'T2_FGM2',
 'T2_FGM2_diff',
 'T2_FGM3',
 'T2_FGM3_diff',
 'T2_FGM_diff',
 'T2_FGM_no_ast',
 'T2_FGM_no_ast_diff',
 'T2_FTA',
 'T2_FTA_diff',
 'T2_FTM',
 'T2_FTM_diff',
 'T2_N_wins',
 'T2_OR',
 'T2_OR_diff',
 'T2_OR_opportunity',
 'T2_OR_opportunity_diff',
 'T2_OT_win',
 'T2_PF',
 'T2_PF_diff',
 'T2_Score',
 'T2_Score_diff',
 'T2_Stl',
 'T2_Stl_diff',
 'T2_TO',
 'T2_TO_diff',
 'T2_TO_perposs',
 'T2_TO_perposs_diff',
 'T2_Tot_Reb',
 'T2_Tot_Reb_diff',
 'T2_True_shooting_perc_diff',
 'T2_def_rating',
 'T2_impact',
 'T2_impact_diff',
 'T2_off_rating',
 'T2_off_rating_diff',
 'T2_opp_FGA',
 'T2_opp_FGM',
 'T2_opp_FGM3',
 'T2_opp_FTA',
 'T2_opp_PF',
 'T2_opp_TO',
 'T2_opp_possessions',
 'T2_opp_score',
 'T2_opp_shtg_opportunity',
 'T2_possessions',
 'T2_possessions_diff',
 'T2_shtg_opportunity',
 'T2_shtg_opportunity_diff',
 'T2_FGM_perc',
 'T2_FGM2_perc',
 'T2_FGM3_perc',
 'T2_FT_perc',
 'T2_FGM_no_ast_perc',
 'T2_True_shooting_perc',
 'T2_Opp_True_shooting_perc',
 'T2_Eff_shooting_perc',
 'T2_Opp_eff_shooting_perc',
 'T2_OT_win_perc',
 'T2_elo',
 'delta_Ast',
 'delta_Ast_TO_ratio',
 'delta_Ast_TO_ratio_diff',
 'delta_Ast_diff',
 'delta_Away',
 'delta_Blk',
 'delta_Blk_diff',
 'delta_DR',
 'delta_DR_diff',
 'delta_DR_opportunity',
 'delta_DR_opportunity_diff',
 'delta_Eff_FG_perc_diff',
 'delta_FG3_ratio',
 'delta_FG3_ratio_diff',
 'delta_FGA',
 'delta_FGA2',
 'delta_FGA2_diff',
 'delta_FGA3',
 'delta_FGA3_diff',
 'delta_FGA_diff',
 'delta_FGM',
 'delta_FGM2',
 'delta_FGM2_diff',
 'delta_FGM3',
 'delta_FGM3_diff',
 'delta_FGM_diff',
 'delta_FGM_no_ast',
 'delta_FGM_no_ast_diff',
 'delta_FTA',
 'delta_FTA_diff',
 'delta_FTM',
 'delta_FTM_diff',
 'delta_N_wins',
 'delta_OR',
 'delta_OR_diff',
 'delta_OR_opportunity',
 'delta_OR_opportunity_diff',
 'delta_OT_win',
 'delta_PF',
 'delta_PF_diff',
 'delta_Score',
 'delta_Score_diff',
 'delta_Stl',
 'delta_Stl_diff',
 'delta_TO',
 'delta_TO_diff',
 'delta_TO_perposs',
 'delta_TO_perposs_diff',
 'delta_Tot_Reb',
 'delta_Tot_Reb_diff',
 'delta_True_shooting_perc_diff',
 'delta_def_rating',
 'delta_impact',
 'delta_off_rating',
 'delta_off_rating_diff',
 'delta_opp_FGA',
 'delta_opp_FGM',
 'delta_opp_FGM3',
 'delta_opp_FTA',
 'delta_opp_PF',
 'delta_opp_TO',
 'delta_opp_possessions',
 'delta_opp_score',
 'delta_opp_shtg_opportunity',
 'delta_possessions',
 'delta_possessions_diff',
 'delta_shtg_opportunity',
 'delta_shtg_opportunity_diff',
 'delta_FGM_perc',
 'delta_FGM2_perc',
 'delta_FGM3_perc',
 'delta_FT_perc',
 'delta_FGM_no_ast_perc',
 'delta_True_shooting_perc',
 'delta_Opp_True_shooting_perc',
 'delta_Eff_shooting_perc',
 'delta_Opp_eff_shooting_perc',
 'delta_OT_win_perc',
 'delta_elo',
 'delta_off_edge',
 'delta_def_edge',
 'stage_Round1',
 'stage_Round2',
 'stage_Round3',
 'stage_Round4',
 'stage_final',
 'stage_finalfour',
 'stage_impossible',
 'T1_quality',
 'T2_quality',
 'delta_quality',
 'tourney']

In [8]:
feats_dict = {"all_feats": all_feats,
              "all_delta": all_delta, "no_delta": no_delta, "no_seeds": no_seeds, "seeds": seeds}

# Points predictions

## LGBM

In [9]:
def objective(trial, data=df_train, target=df_train["target_points"]):
    param = {
        "max_depth": trial.suggest_int("max_depth", 3, 200),
        "num_leaves": trial.suggest_int("num_leaves", 10, 100),
        'reg_lambda': trial.suggest_float('reg_lambda', 1e-3, 100.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-3, 100.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.3, 1),
        'subsample': trial.suggest_float('subsample', 0.4, 1),
        'min_child_weight': trial.suggest_float('min_child_weight', 1e-3 , 300),
        'feats': trial.suggest_categorical("feats", list(feats_dict.keys())),
        "clip_val": trial.suggest_int("clip_val", 20, 50),
        "padd": trial.suggest_float("padd", 0, 0.05)
        # "agg_func": trial.suggest_categorical("agg_func", ["mean", "median", "std"]),
        # "formula": trial.suggest_categorical("formula", [True, False])
    }
    
        
    train = data.copy()

    FEATURES = feats_dict[param["feats"]]


    num_pipe = Pipeline([('sel', tml.DtypeSel('numeric')),
                        ('imputer', tml.DfImputer(strategy='mean')),
                        ])

    processing_pipe = tml.FeatureUnionDf(transformer_list=[('num', num_pipe),
                                                        #('cat_means', cat_pipe)
                                                        ])
        
    model = lgb.LGBMRegressor(random_state=34, n_jobs=-1, verbose=-1, n_estimators=10000,
                              learning_rate=0.1,
                             colsample_bytree=param["colsample_bytree"],
                             min_child_weight=param['min_child_weight'],
                             reg_lambda=param['reg_lambda'],
                             reg_alpha=param['reg_alpha'],
                             subsample=param['subsample'],
                             num_leaves=param["num_leaves"],
                             max_depth=param['max_depth'],
                             eval_metric="l2")

    pipe = Pipeline([ #("fe", FeatEng(formula=param["formula"])),
                        ("processing", processing_pipe),

                    ("model", model)])
    
    callbacks = [lgb.early_stopping(100, verbose=0)]
    
    fit_params = {"callbacks":callbacks, "eval_metric": "l2"}

    cvscore = tml.CrossValidate(data=train[FEATURES], target=target, cv=kfolds, estimator=pipe, fit_params=fit_params, early_stopping=True)
    oof, _ = cvscore.score()

    spline_oof, _ = _point_to_proba(oof, target, oof, clip_val=param["clip_val"], padd=param["padd"])

    score = brier_score_loss(np.where(target > 0, 1, 0), y_prob=spline_oof)
    
    return score

In [10]:
sampler = TPESampler(seed=645)  # Make the sampler behave in a deterministic way.

study = optuna.create_study(direction='minimize', sampler=sampler)
optuna.logging.set_verbosity(optuna.logging.WARNING)
study.optimize(objective, n_trials=1000, n_jobs=-1)
print('Number of finished trials:', len(study.trials))
print('Best trial:', study.best_trial.params)

[I 2026-03-08 08:39:33,436] A new study created in memory with name: no-name-3521ce27-d184-45fd-afde-4480879ab716
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast

Number of finished trials: 1000
Best trial: {'max_depth': 90, 'num_leaves': 13, 'reg_lambda': 11.865936878578008, 'reg_alpha': 20.532514349965357, 'colsample_bytree': 0.46526214114851555, 'subsample': 0.4405185534411223, 'min_child_weight': 4.662880615219311, 'feats': 'all_delta', 'clip_val': 23, 'padd': 0.04124760745742165}

In [11]:
0.183152

0.183152

In [12]:
study.trials_dataframe().sort_values('value', ascending=True).head(20)

,number,value,datetime_start,datetime_complete,duration,params_clip_val,params_colsample_bytree,params_feats,params_max_depth,params_min_child_weight,params_num_leaves,params_padd,params_reg_alpha,params_reg_lambda,params_subsample,state
896,896,0.165223,2026-03-08 09:08:38.045697,2026-03-08 09:09:02.478910,0 days 00:00:24.433213,23,0.465262,all_delta,90,4.662881,13,0.041248,20.532514,11.865937,0.440519,COMPLETE
919,919,0.165267,2026-03-08 09:09:10.207504,2026-03-08 09:09:32.854743,0 days 00:00:22.647239,22,0.443757,all_delta,74,0.665615,10,0.038369,22.466277,8.727274,0.677269,COMPLETE
657,657,0.165284,2026-03-08 09:02:25.944359,2026-03-08 09:02:44.463992,0 days 00:00:18.519633,25,0.461739,all_delta,51,13.993919,13,0.042001,33.951447,15.813333,0.486228,COMPLETE
757,757,0.165286,2026-03-08 09:05:07.247985,2026-03-08 09:05:28.257015,0 days 00:00:21.009030,23,0.518415,all_delta,72,56.215584,13,0.035877,7.276913,5.322231,0.942060,COMPLETE
409,409,0.165321,2026-03-08 08:56:12.807364,2026-03-08 08:56:40.065992,0 days 00:00:27.258628,24,0.473596,all_delta,62,18.760913,12,0.044137,30.764173,13.639863,0.862510,COMPLETE
986,986,0.165337,2026-03-08 09:10:49.061534,2026-03-08 09:11:12.212394,0 days 00:00:23.150860,20,0.411780,all_delta,90,0.264160,16,0.032475,21.489488,2.411309,0.673558,COMPLETE
965,965,0.165358,2026-03-08 09:10:19.624973,2026-03-08 09:10:42.162861,0 days 00:00:22.537888,20,0.461415,all_delta,94,1.114113,12,0.035620,17.941856,9.856678,0.630014,COMPLETE
961,961,0.165361,2026-03-08 09:10:13.771342,2026-03-08 09:10:34.160245,0 days 00:00:20.388903,21,0.460947,all_delta,89,0.303680,12,0.035044,20.699644,10.124168,0.694314,COMPLETE
797,797,0.165367,2026-03-08 09:06:10.228562,2026-03-08 09:06:31.632664,0 days 00:00:21.404102,24,0.533478,all_delta,81,37.805883,15,0.035130,11.110234,4.328134,0.416894,COMPLETE
706,706,0.165383,2026-03-08 09:03:45.219791,2026-03-08 09:04:03.672995,0 days 00:00:18.453204,24,0.683460,all_delta,42,28.275477,12,0.037152,27.811190,13.944548,0.403106,COMPLETE
507,507,0.165387,2026-03-08 08:58:52.170624,2026-03-08 08:59:13.451581,0 days 00:00:21.280957,25,0.690181,all_delta,8,19.214435,12,0.038613,23.692419,14.817012,0.846468,COMPLETE
459,459,0.165389,2026-03-08 08:57:31.539085,2026-03-08 08:57:51.432953,0 days 00:00:19.893868,25,0.515531,all_delta,3,0.317353,13,0.039815,22.336647,8.572514,0.903187,COMPLETE
926,926,0.165414,2026-03-08 09:09:25.662839,2026-03-08 09:09:46.221518,0 days 00:00:20.558679,22,0.455001,all_delta,102,22.582071,10,0.038108,21.394665,8.801795,0.427524,COMPLETE
537,537,0.165414,2026-03-08 08:59:31.210712,2026-03-08 08:59:49.986466,0 days 00:00:18.775754,24,0.718078,all_delta,66,27.704266,13,0.038492,16.027720,16.989452,0.893660,COMPLETE
934,934,0.165414,2026-03-08 09:09:32.860582,2026-03-08 09:09:55.817832,0 days 00:00:22.957250,21,0.433598,all_delta,97,0.272243,11,0.036552,24.366961,9.454729,0.614254,COMPLETE
445,445,0.165415,2026-03-08 08:57:12.230022,2026-03-08 08:57:39.268748,0 days 00:00:27.038726,23,0.657301,all_delta,11,0.025072,13,0.040469,28.791254,11.581654,0.886830,COMPLETE
592,592,0.165443,2026-03-08 09:00:44.533304,2026-03-08 09:01:06.291284,0 days 00:00:21.757980,24,0.676893,all_delta,45,13.967504,12,0.038656,26.204503,14.008419,0.457365,COMPLETE
765,765,0.165457,2026-03-08 09:05:24.019139,2026-03-08 09:05:41.046874,0 days 00:00:17.027735,23,0.515966,all_delta,77,30.856823,12,0.030785,12.856542,2.345638,0.412817,COMPLETE
442,442,0.165461,2026-03-08 08:57:07.547791,2026-03-08 08:57:28.730475,0 days 00:00:21.182684,24,0.489885,all_delta,18,6.004463,13,0.040703,28.014744,10.998373,0.889871,COMPLETE
969,969,0.165469,2026-03-08 09:10:26.434904,2026-03-08 09:10:50.860386,0 days 00:00:24.425482,20,0.465136,all_delta,102,2.066144,12,0.033669,20.141790,1.289054,0.639533,COMPLETE

## XGBoost

In [13]:
def objective(trial, data=df_train, target=df_train["target_points"]):
    param = {
        "max_depth": trial.suggest_int("max_depth", 3, 200),
        'reg_lambda': trial.suggest_float('reg_lambda', 1e-3, 100.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-3, 100.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.3, 1),
        "colsample_bylevel": trial.suggest_float("colsample_bylevel", 0.3, 1),
        'subsample': trial.suggest_float('subsample', 0.4, 1),
        'min_child_weight': trial.suggest_float('min_child_weight', 1e-3 , 300),
        'feats': trial.suggest_categorical("feats", list(feats_dict.keys())),
        "clip_val": trial.suggest_int("clip_val", 20, 50),
        "padd": trial.suggest_float("padd", 0, 0.05)
        # "agg_func": trial.suggest_categorical("agg_func", ["mean", "median", "std"]),
        # "formula": trial.suggest_categorical("formula", [True, False])
    }
    
        
    train = data.copy()

    FEATURES = feats_dict[param["feats"]]


    num_pipe = Pipeline([('sel', tml.DtypeSel('numeric')),
                        ('imputer', tml.DfImputer(strategy='mean')),
                        ])

    processing_pipe = tml.FeatureUnionDf(transformer_list=[('num', num_pipe),
                                                        #('cat_means', cat_pipe)
                                                        ])
        
    model = xgb.XGBRegressor(random_state=34, n_jobs=-1, n_estimators=10000,
                              learning_rate=0.1,
                             subsample=param["subsample"],
                            colsample_bytree=param["colsample_bytree"],
                            reg_alpha=param["reg_alpha"],
                            reg_lambda=param["reg_lambda"],
                            max_depth=param["max_depth"],
                            colsample_bylevel=param["colsample_bylevel"],
                            early_stopping_rounds=100,
                             eval_metric=mean_squared_error)

    pipe = Pipeline([ #("fe", FeatEng(formula=param["formula"])),
                        ("processing", processing_pipe),

                    ("model", model)])
    
    
    fit_params = {'verbose': False}

    cvscore = tml.CrossValidate(data=train[FEATURES], target=target, cv=kfolds, estimator=pipe, fit_params=fit_params, early_stopping=True)
    oof, _ = cvscore.score()

    spline_oof, _ = _point_to_proba(oof, target, oof, clip_val=param["clip_val"], padd=param["padd"])

    score = brier_score_loss(np.where(target > 0, 1, 0), y_prob=spline_oof)
    
    return score

In [14]:
sampler = TPESampler(seed=645)  # Make the sampler behave in a deterministic way.

study = optuna.create_study(direction='minimize', sampler=sampler)
optuna.logging.set_verbosity(optuna.logging.WARNING)
study.optimize(objective, n_trials=1000, n_jobs=-1)
print('Number of finished trials:', len(study.trials))
print('Best trial:', study.best_trial.params)

study.trials_dataframe().sort_values('value', ascending=True).head(20)

Number of finished trials: 1000
Best trial: {'max_depth': 3, 'reg_lambda': 12.738494759481998, 'reg_alpha': 19.202063857291815, 'colsample_bytree': 0.970208060904755, 'colsample_bylevel': 0.6628404550150686, 'subsample': 0.9348070408543836, 'min_child_weight': 124.29945187980685, 'feats': 'all_delta', 'clip_val': 20, 'padd': 0.00905924560132836}

,number,value,datetime_start,datetime_complete,duration,params_clip_val,params_colsample_bylevel,params_colsample_bytree,params_feats,params_max_depth,params_min_child_weight,params_padd,params_reg_alpha,params_reg_lambda,params_subsample,state
777,777,0.165296,2026-03-08 12:09:45.724814,2026-03-08 12:11:23.548965,0 days 00:01:37.824151,20,0.662840,0.970208,all_delta,3,124.299452,0.009059,19.202064,12.738495,0.934807,COMPLETE
764,764,0.165388,2026-03-08 12:08:02.307055,2026-03-08 12:09:45.718432,0 days 00:01:43.411377,22,0.667144,0.968823,all_delta,3,132.220532,0.008391,19.009442,18.966694,0.975144,COMPLETE
775,775,0.165637,2026-03-08 12:09:41.688801,2026-03-08 12:11:18.261612,0 days 00:01:36.572811,20,0.665183,0.947559,all_delta,3,122.234421,0.008894,18.480501,18.879752,0.938444,COMPLETE
854,854,0.165718,2026-03-08 12:25:40.292103,2026-03-08 12:27:01.887822,0 days 00:01:21.595719,20,0.681514,0.965278,all_delta,3,156.253200,0.008384,20.565067,19.520474,0.937520,COMPLETE
953,953,0.165731,2026-03-08 12:40:29.692949,2026-03-08 12:41:50.616555,0 days 00:01:20.923606,22,0.675067,0.948704,all_delta,3,161.000716,0.008634,18.168024,18.824047,0.905328,COMPLETE
723,723,0.165749,2026-03-08 12:00:19.413747,2026-03-08 12:01:27.623201,0 days 00:01:08.209454,23,0.696401,0.939500,all_delta,3,134.425982,0.008521,19.951462,17.570152,0.963089,COMPLETE
598,598,0.165763,2026-03-08 11:38:41.636095,2026-03-08 11:39:56.226013,0 days 00:01:14.589918,21,0.674696,0.975790,all_delta,3,112.467238,0.041078,27.854238,17.877329,0.941530,COMPLETE
766,766,0.165831,2026-03-08 12:08:16.431628,2026-03-08 12:09:54.613046,0 days 00:01:38.181418,22,0.666233,0.968376,all_delta,3,144.461179,0.009659,18.216983,19.014008,0.974077,COMPLETE
659,659,0.165837,2026-03-08 11:49:02.796560,2026-03-08 11:50:57.333267,0 days 00:01:54.536707,22,0.640222,0.950950,all_delta,3,115.252742,0.009294,30.221988,22.245074,0.946182,COMPLETE
852,852,0.165841,2026-03-08 12:25:32.368319,2026-03-08 12:26:54.178006,0 days 00:01:21.809687,20,0.684968,0.967236,all_delta,3,159.855276,0.008167,22.130900,20.310193,0.933842,COMPLETE
850,850,0.165906,2026-03-08 12:25:17.714791,2026-03-08 12:26:41.484159,0 days 00:01:23.769368,20,0.679974,0.974282,all_delta,3,156.943617,0.008287,21.949591,20.188185,0.937649,COMPLETE
779,779,0.165965,2026-03-08 12:09:58.335243,2026-03-08 12:11:26.933774,0 days 00:01:28.598531,22,0.815206,0.969484,all_delta,3,123.739232,0.009102,19.060139,18.457976,0.941681,COMPLETE
914,914,0.165971,2026-03-08 12:35:25.808112,2026-03-08 12:37:00.053086,0 days 00:01:34.244974,22,0.667258,0.972830,all_delta,3,142.082232,0.011630,16.325605,15.228116,0.962864,COMPLETE
595,595,0.165974,2026-03-08 11:38:27.224941,2026-03-08 11:39:39.771381,0 days 00:01:12.546440,21,0.574945,0.845893,all_delta,3,161.460646,0.014118,94.686608,17.010494,0.998004,COMPLETE
597,597,0.165977,2026-03-08 11:38:31.441932,2026-03-08 11:39:44.759239,0 days 00:01:13.317307,21,0.671160,0.956591,all_delta,3,113.808961,0.018270,28.857702,17.919515,0.944951,COMPLETE
377,377,0.165981,2026-03-08 10:54:59.714217,2026-03-08 10:56:27.207304,0 days 00:01:27.493087,20,0.483169,0.686022,all_delta,6,75.673181,0.015851,30.619103,83.813579,0.999856,COMPLETE
842,842,0.165999,2026-03-08 12:24:14.563982,2026-03-08 12:25:28.105994,0 days 00:01:13.542012,21,0.935036,0.969483,all_delta,3,154.921545,0.008248,19.306989,19.952527,0.952440,COMPLETE
951,951,0.166000,2026-03-08 12:40:22.594387,2026-03-08 12:41:47.343863,0 days 00:01:24.749476,22,0.672689,0.947769,all_delta,3,128.000030,0.008469,13.380985,19.776559,0.901496,COMPLETE
774,774,0.166000,2026-03-08 12:09:33.519453,2026-03-08 12:10:56.747642,0 days 00:01:23.228189,20,0.820634,0.965436,all_delta,3,144.835544,0.009190,19.472344,12.857970,0.936336,COMPLETE
712,712,0.166022,2026-03-08 11:58:38.159066,2026-03-08 12:00:05.698613,0 days 00:01:27.539547,22,0.679870,0.841470,all_delta,3,132.929587,0.009716,15.460962,21.228223,0.965074,COMPLETE

## Ridge

In [15]:
def objective(trial, data=df_train, target=df_train["target_points"]):
    param = {
        "alpha": trial.suggest_float("alpha", 0.1, 200),
        'feats': trial.suggest_categorical("feats", list(feats_dict.keys())),
        "clip_val": trial.suggest_int("clip_val", 20, 50),
        "padd": trial.suggest_float("padd", 0, 0.05)
    }
    
        
    train = data.copy()

    FEATURES = feats_dict[param["feats"]]


    num_pipe = Pipeline([('sel', tml.DtypeSel('numeric')),
                        ('imputer', tml.DfImputer(strategy='mean')),
                        ])

    processing_pipe = tml.FeatureUnionDf(transformer_list=[('num', num_pipe),
                                                        #('cat_means', cat_pipe)
                                                        ])
        
    model = Ridge(random_state=34, alpha=param["alpha"], max_iter=10000)

    pipe = Pipeline([ #("fe", FeatEng(formula=param["formula"])),
                        ("processing", processing_pipe),
                        ("scaler", tml.DfScaler()),

                    ("model", model)])
    

    cvscore = tml.CrossValidate(data=train[FEATURES], target=target, cv=kfolds, estimator=pipe)
    oof, _ = cvscore.score()

    spline_oof, _ = _point_to_proba(oof, target, oof, clip_val=param["clip_val"], padd=param["padd"])

    score = brier_score_loss(np.where(target > 0, 1, 0), y_prob=spline_oof)
    
    return score

In [16]:
sampler = TPESampler(seed=645)  # Make the sampler behave in a deterministic way.

study = optuna.create_study(direction='minimize', sampler=sampler)
optuna.logging.set_verbosity(optuna.logging.WARNING)
study.optimize(objective, n_trials=2000, n_jobs=-1)
print('Number of finished trials:', len(study.trials))
print('Best trial:', study.best_trial.params)

study.trials_dataframe().sort_values('value', ascending=True).head(20)

Number of finished trials: 2000
Best trial: {'alpha': 10.648932219848346, 'feats': 'all_delta', 'clip_val': 23, 'padd': 0.01971647622688984}

,number,value,datetime_start,datetime_complete,duration,params_alpha,params_clip_val,params_feats,params_padd,state
1530,1530,0.165357,2026-03-08 13:20:46.765302,2026-03-08 13:21:02.481146,0 days 00:00:15.715844,10.648932,23,all_delta,0.019716,COMPLETE
1595,1595,0.165358,2026-03-08 13:21:50.244070,2026-03-08 13:22:09.017067,0 days 00:00:18.772997,10.813360,23,all_delta,0.010444,COMPLETE
581,581,0.165358,2026-03-08 13:04:13.021250,2026-03-08 13:04:24.769390,0 days 00:00:11.748140,10.798193,23,all_delta,0.008961,COMPLETE
1585,1585,0.165358,2026-03-08 13:21:35.300474,2026-03-08 13:21:49.795862,0 days 00:00:14.495388,10.705163,23,all_delta,0.010687,COMPLETE
610,610,0.165358,2026-03-08 13:05:04.437008,2026-03-08 13:05:22.648856,0 days 00:00:18.211848,10.673745,23,all_delta,0.011586,COMPLETE
613,613,0.165358,2026-03-08 13:05:06.614007,2026-03-08 13:05:23.822798,0 days 00:00:17.208791,10.662603,23,all_delta,0.011468,COMPLETE
909,909,0.165358,2026-03-08 13:10:16.346384,2026-03-08 13:10:32.479001,0 days 00:00:16.132617,10.878121,23,all_delta,0.011148,COMPLETE
588,588,0.165358,2026-03-08 13:04:22.896701,2026-03-08 13:04:37.027466,0 days 00:00:14.130765,10.609078,23,all_delta,0.008677,COMPLETE
1779,1779,0.165358,2026-03-08 13:25:15.503826,2026-03-08 13:25:28.680716,0 days 00:00:13.176890,10.517503,23,all_delta,0.012581,COMPLETE
974,974,0.165358,2026-03-08 13:11:14.881629,2026-03-08 13:11:31.202478,0 days 00:00:16.320849,10.899163,23,all_delta,0.009032,COMPLETE
912,912,0.165358,2026-03-08 13:10:20.344976,2026-03-08 13:10:38.422561,0 days 00:00:18.077585,10.938393,23,all_delta,0.010087,COMPLETE
838,838,0.165358,2026-03-08 13:08:53.860231,2026-03-08 13:09:10.732813,0 days 00:00:16.872582,10.942488,23,all_delta,0.011456,COMPLETE
1472,1472,0.165358,2026-03-08 13:20:01.005560,2026-03-08 13:20:14.278423,0 days 00:00:13.272863,10.946118,23,all_delta,0.011998,COMPLETE
582,582,0.165358,2026-03-08 13:04:17.998000,2026-03-08 13:04:29.670947,0 days 00:00:11.672947,10.962156,23,all_delta,0.008978,COMPLETE
1382,1382,0.165358,2026-03-08 13:18:33.607903,2026-03-08 13:18:48.953458,0 days 00:00:15.345555,10.971065,23,all_delta,0.008963,COMPLETE
907,907,0.165358,2026-03-08 13:10:15.051344,2026-03-08 13:10:31.662701,0 days 00:00:16.611357,10.979912,23,all_delta,0.010094,COMPLETE
1605,1605,0.165358,2026-03-08 13:22:10.616336,2026-03-08 13:22:23.850560,0 days 00:00:13.234224,11.005591,23,all_delta,0.007935,COMPLETE
1388,1388,0.165358,2026-03-08 13:18:39.264620,2026-03-08 13:18:56.422180,0 days 00:00:17.157560,11.018480,23,all_delta,0.008772,COMPLETE
1389,1389,0.165358,2026-03-08 13:18:39.559804,2026-03-08 13:18:56.465413,0 days 00:00:16.905609,11.029293,23,all_delta,0.008728,COMPLETE
911,911,0.165358,2026-03-08 13:10:20.107159,2026-03-08 13:10:35.586612,0 days 00:00:15.479453,11.031471,23,all_delta,0.009986,COMPLETE

## Lasso

In [17]:
def objective(trial, data=df_train, target=df_train["target_points"]):
    param = {
        "alpha": trial.suggest_float("alpha", 0.1, 200),
        'feats': trial.suggest_categorical("feats", list(feats_dict.keys())),
        "clip_val": trial.suggest_int("clip_val", 20, 50),
        "padd": trial.suggest_float("padd", 0, 0.05)
    }
    
        
    train = data.copy()

    FEATURES = feats_dict[param["feats"]]


    num_pipe = Pipeline([('sel', tml.DtypeSel('numeric')),
                        ('imputer', tml.DfImputer(strategy='mean')),
                        ])

    processing_pipe = tml.FeatureUnionDf(transformer_list=[('num', num_pipe),
                                                        #('cat_means', cat_pipe)
                                                        ])
        
    model = Lasso(random_state=34, alpha=param["alpha"], max_iter=10000)

    pipe = Pipeline([ #("fe", FeatEng(formula=param["formula"])),
                        ("processing", processing_pipe),
                        ("scaler", tml.DfScaler()),

                    ("model", model)])
    

    cvscore = tml.CrossValidate(data=train[FEATURES], target=target, cv=kfolds, estimator=pipe)
    oof, _ = cvscore.score()

    spline_oof, _ = _point_to_proba(oof, target, oof, clip_val=param["clip_val"], padd=param["padd"])

    score = brier_score_loss(np.where(target > 0, 1, 0), y_prob=spline_oof)
    
    return score

In [18]:
sampler = TPESampler(seed=645)  # Make the sampler behave in a deterministic way.

study = optuna.create_study(direction='minimize', sampler=sampler)
optuna.logging.set_verbosity(optuna.logging.WARNING)
study.optimize(objective, n_trials=2000, n_jobs=-1)
print('Number of finished trials:', len(study.trials))
print('Best trial:', study.best_trial.params)

study.trials_dataframe().sort_values('value', ascending=True).head(20)

invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast
is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
invalid value encountered in cast

Number of finished trials: 2000
Best trial: {'alpha': 0.11287575902911327, 'feats': 'all_delta', 'clip_val': 23, 'padd': 0.011351441200606549}

,number,value,datetime_start,datetime_complete,duration,params_alpha,params_clip_val,params_feats,params_padd,state
1161,1161,0.165694,2026-03-08 13:55:23.183678,2026-03-08 13:55:35.999400,0 days 00:00:12.815722,0.112876,23,all_delta,0.011351,COMPLETE
845,845,0.165694,2026-03-08 13:49:52.451577,2026-03-08 13:50:09.453135,0 days 00:00:17.001558,0.111643,23,all_delta,0.009665,COMPLETE
1558,1558,0.165694,2026-03-08 14:02:15.402462,2026-03-08 14:02:28.330290,0 days 00:00:12.927828,0.114506,23,all_delta,0.014486,COMPLETE
1850,1850,0.165694,2026-03-08 14:07:38.288694,2026-03-08 14:07:52.956723,0 days 00:00:14.668029,0.114406,23,all_delta,0.018241,COMPLETE
840,840,0.165695,2026-03-08 13:49:48.946002,2026-03-08 13:50:02.472382,0 days 00:00:13.526380,0.114854,23,all_delta,0.009461,COMPLETE
1914,1914,0.165696,2026-03-08 14:08:44.262955,2026-03-08 14:09:01.539452,0 days 00:00:17.276497,0.116082,23,all_delta,0.017233,COMPLETE
1565,1565,0.165696,2026-03-08 14:02:21.423139,2026-03-08 14:02:37.740094,0 days 00:00:16.316955,0.109061,23,all_delta,0.015129,COMPLETE
1590,1590,0.165697,2026-03-08 14:02:42.332527,2026-03-08 14:02:57.208235,0 days 00:00:14.875708,0.110366,24,all_delta,0.014855,COMPLETE
1345,1345,0.165699,2026-03-08 13:58:22.122283,2026-03-08 13:58:34.132191,0 days 00:00:12.009908,0.113487,22,all_delta,0.009983,COMPLETE
701,701,0.165700,2026-03-08 13:47:12.055586,2026-03-08 13:47:28.223876,0 days 00:00:16.168290,0.112434,22,all_delta,0.013996,COMPLETE
971,971,0.165700,2026-03-08 13:51:57.155399,2026-03-08 13:52:12.318491,0 days 00:00:15.163092,0.112207,22,all_delta,0.021597,COMPLETE
1223,1223,0.165701,2026-03-08 13:56:22.546410,2026-03-08 13:56:35.883332,0 days 00:00:13.336922,0.104458,23,all_delta,0.020368,COMPLETE
344,344,0.165701,2026-03-08 13:39:40.906515,2026-03-08 13:39:54.648837,0 days 00:00:13.742322,0.105930,24,all_delta,0.009158,COMPLETE
1505,1505,0.165702,2026-03-08 14:01:09.931034,2026-03-08 14:01:24.637177,0 days 00:00:14.706143,0.116255,22,all_delta,0.016183,COMPLETE
589,589,0.165703,2026-03-08 13:45:32.566334,2026-03-08 13:45:46.845426,0 days 00:00:14.279092,0.117308,22,all_delta,0.013635,COMPLETE
584,584,0.165704,2026-03-08 13:45:27.474994,2026-03-08 13:45:40.045805,0 days 00:00:12.570811,0.108275,22,all_delta,0.020226,COMPLETE
934,934,0.165704,2026-03-08 13:51:19.413874,2026-03-08 13:51:30.802135,0 days 00:00:11.388261,0.107840,22,all_delta,0.011223,COMPLETE
1652,1652,0.165704,2026-03-08 14:03:41.527450,2026-03-08 14:03:56.167129,0 days 00:00:14.639679,0.122106,23,all_delta,0.017520,COMPLETE
494,494,0.165705,2026-03-08 13:44:05.662368,2026-03-08 13:44:18.159663,0 days 00:00:12.497295,0.122547,23,all_delta,0.009419,COMPLETE
1866,1866,0.165705,2026-03-08 14:07:52.962331,2026-03-08 14:08:09.819168,0 days 00:00:16.856837,0.121710,24,all_delta,0.018405,COMPLETE

# Probability Predictions


## LGBM

In [19]:
def objective(trial, data=df_train, target=df_train["target"]):
    param = {
        "max_depth": trial.suggest_int("max_depth", 3, 200),
        "num_leaves": trial.suggest_int("num_leaves", 10, 100),
        'reg_lambda': trial.suggest_float('reg_lambda', 1e-3, 100.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-3, 100.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.3, 1),
        'subsample': trial.suggest_float('subsample', 0.4, 1),
        'min_child_weight': trial.suggest_float('min_child_weight', 1e-3 , 300),
        'feats': trial.suggest_categorical("feats", list(feats_dict.keys())),
    }
    
        
    train = data.copy()

    FEATURES = feats_dict[param["feats"]]


    num_pipe = Pipeline([('sel', tml.DtypeSel('numeric')),
                        ('imputer', tml.DfImputer(strategy='mean')),
                        ])

    processing_pipe = tml.FeatureUnionDf(transformer_list=[('num', num_pipe),
                                                        #('cat_means', cat_pipe)
                                                        ])
        
    model = lgb.LGBMClassifier(random_state=34, n_jobs=-1, verbose=-1, n_estimators=10000,
                               learning_rate=0.1,
                             colsample_bytree=param["colsample_bytree"],
                             min_child_weight=param['min_child_weight'],
                             reg_lambda=param['reg_lambda'],
                             reg_alpha=param['reg_alpha'],
                             subsample=param['subsample'],
                             num_leaves=param["num_leaves"],
                             max_depth=param['max_depth'],
                             eval_metric="auc")

    pipe = Pipeline([ #("fe", FeatEng(formula=param["formula"])),
                        ("processing", processing_pipe),

                    ("model", model)])
    
    callbacks = [lgb.early_stopping(100, verbose=0)]
    
    fit_params = {"callbacks":callbacks, "eval_metric": "auc"}

    cvscore = tml.CrossValidate(data=train[FEATURES], target=target, cv=kfolds, estimator=pipe, fit_params=fit_params, early_stopping=True, predict_proba=True)
    oof, _ = cvscore.score()

    score = brier_score_loss(target, y_prob=oof)
    
    return score

In [20]:
sampler = TPESampler(seed=645)  # Make the sampler behave in a deterministic way.

study = optuna.create_study(direction='minimize', sampler=sampler)
optuna.logging.set_verbosity(optuna.logging.WARNING)
study.optimize(objective, n_trials=1000, n_jobs=-1)
print('Number of finished trials:', len(study.trials))
print('Best trial:', study.best_trial.params)

study.trials_dataframe().sort_values('value', ascending=True).head(20)

Number of finished trials: 1000
Best trial: {'max_depth': 195, 'num_leaves': 21, 'reg_lambda': 21.390761919810387, 'reg_alpha': 0.06309806111703037, 'colsample_bytree': 0.882386981850899, 'subsample': 0.9661210930098577, 'min_child_weight': 1.7775885322232414, 'feats': 'all_feats'}

,number,value,datetime_start,datetime_complete,duration,params_colsample_bytree,params_feats,params_max_depth,params_min_child_weight,params_num_leaves,params_reg_alpha,params_reg_lambda,params_subsample,state
436,436,0.165835,2026-03-08 14:22:13.700139,2026-03-08 14:22:58.683136,0 days 00:00:44.982997,0.882387,all_feats,195,1.777589,21,0.063098,21.390762,0.966121,COMPLETE
355,355,0.165855,2026-03-08 14:18:41.197084,2026-03-08 14:19:21.432051,0 days 00:00:40.234967,0.793341,all_feats,193,1.189624,15,2.078816,19.091115,0.777693,COMPLETE
386,386,0.165909,2026-03-08 14:20:02.578265,2026-03-08 14:20:50.800109,0 days 00:00:48.221844,0.965658,all_feats,186,0.019295,23,0.677089,22.012978,0.958314,COMPLETE
962,962,0.166003,2026-03-08 14:43:50.955764,2026-03-08 14:44:30.401547,0 days 00:00:39.445783,0.931712,all_feats,3,9.766706,18,0.018171,18.649508,0.513602,COMPLETE
354,354,0.166010,2026-03-08 14:18:39.718850,2026-03-08 14:19:08.637630,0 days 00:00:28.918780,0.837323,all_feats,3,15.282607,18,2.145178,17.342192,0.993225,COMPLETE
513,513,0.166025,2026-03-08 14:25:45.322543,2026-03-08 14:26:21.758388,0 days 00:00:36.435845,0.890595,all_feats,196,0.448567,20,6.754181,16.638792,0.890751,COMPLETE
393,393,0.166119,2026-03-08 14:20:31.492299,2026-03-08 14:21:14.759657,0 days 00:00:43.267358,0.893751,all_feats,190,4.095319,22,0.128613,22.393022,0.957760,COMPLETE
525,525,0.166122,2026-03-08 14:26:14.131551,2026-03-08 14:27:04.973791,0 days 00:00:50.842240,0.959297,all_feats,184,0.173434,22,0.253634,26.321937,0.975615,COMPLETE
426,426,0.166147,2026-03-08 14:21:58.709603,2026-03-08 14:22:42.564953,0 days 00:00:43.855350,0.884036,all_feats,195,0.517756,22,0.200707,21.801640,0.928085,COMPLETE
304,304,0.166154,2026-03-08 14:17:08.983415,2026-03-08 14:17:35.068545,0 days 00:00:26.085130,0.736141,all_delta,182,18.782104,15,5.372485,13.957803,0.862351,COMPLETE
378,378,0.166155,2026-03-08 14:19:43.312523,2026-03-08 14:20:33.960003,0 days 00:00:50.647480,0.900142,all_feats,190,0.374337,23,0.208221,21.740294,0.996383,COMPLETE
394,394,0.166169,2026-03-08 14:20:32.123966,2026-03-08 14:21:19.541849,0 days 00:00:47.417883,0.897364,all_feats,191,5.798485,26,0.015542,23.855408,0.963728,COMPLETE
334,334,0.166170,2026-03-08 14:18:00.937722,2026-03-08 14:18:32.808479,0 days 00:00:31.870757,0.831118,all_feats,3,7.997567,15,0.525057,16.984784,0.987202,COMPLETE
987,987,0.166174,2026-03-08 14:44:51.071669,2026-03-08 14:45:24.375194,0 days 00:00:33.303525,0.964710,all_feats,3,15.462629,16,2.329394,16.225463,0.483316,COMPLETE
361,361,0.166203,2026-03-08 14:18:58.961918,2026-03-08 14:19:42.423283,0 days 00:00:43.461365,0.923766,all_feats,13,0.035988,18,0.189486,20.576050,0.509304,COMPLETE
635,635,0.166233,2026-03-08 14:30:47.170391,2026-03-08 14:31:30.459007,0 days 00:00:43.288616,0.879197,all_feats,185,0.127099,19,0.194753,20.674162,0.699015,COMPLETE
495,495,0.166246,2026-03-08 14:24:59.319125,2026-03-08 14:25:36.763605,0 days 00:00:37.444480,0.916018,all_feats,193,5.761116,19,6.210623,17.313461,0.927285,COMPLETE
648,648,0.166252,2026-03-08 14:31:19.217102,2026-03-08 14:31:58.652674,0 days 00:00:39.435572,0.894600,all_feats,20,0.235821,15,2.422651,15.247802,0.988364,COMPLETE
335,335,0.166267,2026-03-08 14:18:01.756905,2026-03-08 14:18:35.875445,0 days 00:00:34.118540,0.873545,all_feats,3,4.971450,16,0.353743,18.220004,0.974438,COMPLETE
832,832,0.166289,2026-03-08 14:38:26.581964,2026-03-08 14:38:57.569637,0 days 00:00:30.987673,0.805477,all_feats,3,0.182641,15,3.285777,13.836486,0.978268,COMPLETE

## XGBoost

In [21]:
def objective(trial, data=df_train, target=df_train["target"]):
    param = {
        "max_depth": trial.suggest_int("max_depth", 3, 200),
        'reg_lambda': trial.suggest_float('reg_lambda', 1e-3, 100.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-3, 100.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.3, 1),
        "colsample_bylevel": trial.suggest_float("colsample_bylevel", 0.3, 1),
        'subsample': trial.suggest_float('subsample', 0.4, 1),
        'min_child_weight': trial.suggest_float('min_child_weight', 1e-3 , 300),
        'feats': trial.suggest_categorical("feats", list(feats_dict.keys())),
    }
    
        
    train = data.copy()

    FEATURES = feats_dict[param["feats"]]


    num_pipe = Pipeline([('sel', tml.DtypeSel('numeric')),
                        ('imputer', tml.DfImputer(strategy='mean')),
                        ])

    processing_pipe = tml.FeatureUnionDf(transformer_list=[('num', num_pipe),
                                                        #('cat_means', cat_pipe)
                                                        ])
        
    model = xgb.XGBClassifier(random_state=34, n_jobs=-1, n_estimators=10000,
                              learning_rate=0.1,
                             subsample=param["subsample"],
                            colsample_bytree=param["colsample_bytree"],
                            reg_alpha=param["reg_alpha"],
                            reg_lambda=param["reg_lambda"],
                            max_depth=param["max_depth"],
                            colsample_bylevel=param["colsample_bylevel"],
                            early_stopping_rounds=100,
                             eval_metric="auc")

    pipe = Pipeline([ #("fe", FeatEng(formula=param["formula"])),
                        ("processing", processing_pipe),

                    ("model", model)])
    
    
    fit_params = {"verbose": False}

    cvscore = tml.CrossValidate(data=train[FEATURES], target=target, cv=kfolds, estimator=pipe, fit_params=fit_params, early_stopping=True, predict_proba=True)
    oof, _ = cvscore.score()

    score = brier_score_loss(target, y_prob=oof)
    
    return score

In [ ]:
sampler = TPESampler(seed=645)  # Make the sampler behave in a deterministic way.

study = optuna.create_study(direction='minimize', sampler=sampler)
optuna.logging.set_verbosity(optuna.logging.WARNING)
study.optimize(objective, n_trials=1000, n_jobs=-1)
print('Number of finished trials:', len(study.trials))
print('Best trial:', study.best_trial.params)

study.trials_dataframe().sort_values('value', ascending=True).head(20)

## LogisticRegression

In [ ]:
def objective(trial, data=df_train, target=df_train["target"]):
    param = {
        'C': trial.suggest_float('reg_lambda', 1e-3, 100.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-3, 100.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.3, 1),
        "colsample_bylevel": trial.suggest_float("colsample_bylevel", 0.3, 1),
        'subsample': trial.suggest_float('subsample', 0.4, 1),
        'min_child_weight': trial.suggest_float('min_child_weight', 1e-3 , 300),
        'feats': trial.suggest_categorical("feats", list(feats_dict.keys())),
    }
    
        
    train = data.copy()

    FEATURES = feats_dict[param["feats"]]


    num_pipe = Pipeline([('sel', tml.DtypeSel('numeric')),
                        ('imputer', tml.DfImputer(strategy='mean')),
                        ])

    processing_pipe = tml.FeatureUnionDf(transformer_list=[('num', num_pipe),
                                                        #('cat_means', cat_pipe)
                                                        ])
        
    model = LogisticRegression(C=param["C"], random_state=34, max_iter=10000)

    pipe = Pipeline([ #("fe", FeatEng(formula=param["formula"])),
                        ("processing", processing_pipe),
                        ("scaler", tml.DfScaler()),

                    ("model", model)])
    

    cvscore = tml.CrossValidate(data=train[FEATURES], target=target, cv=kfolds, estimator=pipe, predict_proba=True)
    oof, _ = cvscore.score()

    score = brier_score_loss(target, y_prob=oof)
    
    return score

In [ ]:
sampler = TPESampler(seed=645)  # Make the sampler behave in a deterministic way.

study = optuna.create_study(direction='minimize', sampler=sampler)
optuna.logging.set_verbosity(optuna.logging.WARNING)
study.optimize(objective, n_trials=500, n_jobs=-1)
print('Number of finished trials:', len(study.trials))
print('Best trial:', study.best_trial.params)

study.trials_dataframe().sort_values('value', ascending=True).head(20)